# Generated by Django 5.0.4 on 2024-05-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_booleandefaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='anonymous_only',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to non-logged-in users?', verbose_name='Anonymous only'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to authenticated users?', verbose_name='Login required'),
        ),
    ]
