# Generated by Django 5.0.4 on 2024-04-26 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0002_rename_movie_solspecs_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solspecs',
            name='Specs',
        ),
        migrations.AddField(
            model_name='solspecs',
            name='Specs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ITapp.specs', verbose_name='Характеристика'),
            preserve_default=False,
        ),
    ]
