# Generated by Django 5.0.4 on 2024-04-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0004_solspecs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solspecs',
            name='Solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='ITapp.solution', verbose_name='IT_продукт'),
        ),
    ]
