# Generated by Django 5.0.4 on 2024-05-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0006_menu_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Банер')),
                ('contacts', models.TextField(verbose_name='Наши контакты')),
                ('mapimg', models.ImageField(upload_to='img/', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
