# Generated by Django 5.0.4 on 2024-05-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0007_aboutcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={},
        ),
    ]
