# Generated by Django 5.0.4 on 2024-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0010_alter_aboutcompany_image_alter_aboutcompany_mapimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Банер'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='mapimg',
            field=models.ImageField(upload_to='img/', verbose_name='Карта'),
        ),
    ]
