# Generated by Django 5.0.4 on 2024-05-21 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0011_alter_aboutcompany_image_alter_aboutcompany_mapimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('name', models.TextField(verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.TextField(verbose_name='Компания')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона в формате: '+7-999-999-99-99'", regex='^\\+?7?\\d{9,16}$')])),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
            },
        ),
    ]
