# Generated by Django 5.0.4 on 2024-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0012_userapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-01 00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
