# Generated by Django 5.0.4 on 2024-05-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0013_userapplication_posted_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='posted_on',
        ),
    ]
