# Generated by Django 5.0.4 on 2024-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0014_remove_userapplication_posted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
