# Generated by Django 5.0.4 on 2024-05-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0015_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
