# Generated by Django 5.0.4 on 2024-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0016_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='img/', verbose_name='Банер'),
        ),
    ]
