# Generated by Django 5.0.4 on 2024-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0017_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('deckription', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акция',
            },
        ),
    ]
