# Generated by Django 5.0.4 on 2024-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0019_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_specification',
            field=models.ManyToManyField(to='ITapp.solspecs', verbose_name='Характеристика'),
        ),
    ]
