# Generated by Django 5.0.4 on 2024-05-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0021_rename_solution_specification_solution_solution_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution_specifications',
        ),
        migrations.AlterField(
            model_name='solspecs',
            name='Solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_specifications', to='ITapp.solution', verbose_name='IT_продукт'),
        ),
        migrations.AlterField(
            model_name='solspecs',
            name='Specs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_solutions', to='ITapp.specs', verbose_name='Характеристика'),
        ),
    ]
