# Generated by Django 5.0.4 on 2024-09-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0022_remove_solution_solution_specifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solspecs',
            old_name='Solution',
            new_name='solution',
        ),
        migrations.RenameField(
            model_name='solspecs',
            old_name='Specs',
            new_name='specs',
        ),
        migrations.RenameField(
            model_name='solspecs',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='solution',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
