# Generated by Django 5.0.4 on 2024-09-26 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0024_rename_specs_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
