# Generated by Django 5.0.4 on 2024-09-26 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0025_alter_solution_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
