# Generated by Django 5.0.4 on 2024-09-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0026_alter_solution_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolSpecs',
            new_name='SolutionSpecifications',
        ),
        migrations.AlterModelOptions(
            name='solutionspecifications',
            options={'verbose_name': 'Характеристика IT продукта', 'verbose_name_plural': 'Характеристики IT продуктов'},
        ),
    ]
