# Generated by Django 5.0.4 on 2024-10-11 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0027_rename_solspecs_solutionspecifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'Акции', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='userapplication',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='title',
        ),
        migrations.AddField(
            model_name='purchases',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
