# Generated by Django 5.0.4 on 2024-10-29 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0030_cart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Покупка/Заказ', 'verbose_name_plural': 'Покупки/Заказы'},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='name',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='price',
        ),
        migrations.AddField(
            model_name='purchases',
            name='pay_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='solution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ITapp.solution', verbose_name='IT решение'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
