# Generated by Django 5.0.4 on 2024-11-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0034_remove_order_city_remove_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='addresses',
        ),
    ]
