# Generated by Django 5.0.4 on 2024-11-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITapp', '0035_rename_address_order_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresses',
            new_name='address',
        ),
    ]
